access_account1     = "your_account_name1"
access_account2    = "your_account_name2"
vpc_reg1            = "us-east-1"
vpc_reg2            = "us-east-2"
vpc_cidr_block1     = "30.1.0.0/16"
vpc_cidr_block2     = "30.2.0.0/16"
vpc_count            = "2"
