cloud_type                  = 1
transit_account             = 1
transit_account_name        = "NuSkin-1to1-account"
transit_gateway_name        = "NuSkin-1to1-transit"
transit_gateway_size        = "t3.micro"
ondemand_spoke_gateway_size = "t2.micro"
ondemand_spoke_count        = 1
ondemand_max_account        = 1
ondemand_act_name           = "NuSkin-1to1-spoke-account"
ondemand_gateway_name       = "NuSkin-1to1-spoke"
ondemand_spoke_cidr_prefix  = "10.52"
ondemand_transit_cidr_prefix= "172.16"
