variable "account_name" {}
variable "account_password" {}
variable "aws_account_number" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "controller_ip" {}
variable "controller_username" {}
variable "controller_password" {}
variable "region1" {}
variable "onprem_cidr" {}
variable "t2instance" {}
variable "conn_name1" {}
variable "conn_name2" {}
variable "remote_subnet1" {}
variable "remote_subnet2" {}
